-- Supabase/PostgreSQL version of the Part I Oracle DDL.
-- This is the recommended backend schema for Part II because it preserves
-- the original Part I HWL_* tables and adds only the web-app tables needed
-- for Supabase Auth, employees, claims, RLS, and demo workflows.

create extension if not exists "pgcrypto";

-- ============================================================
-- 1. Supabase Auth Mapping Tables
-- ============================================================

create table if not exists public.hwl_app_profile (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'customer' check (role in ('customer', 'employee')),
  email text not null unique,
  full_name text,
  phone text,
  created_at timestamptz not null default now()
);

create table if not exists public.hwl_employee (
  emp_id integer generated by default as identity primary key,
  user_id uuid not null unique references public.hwl_app_profile(user_id) on delete cascade,
  emp_fname varchar(50) not null,
  emp_lname varchar(50) not null,
  email text not null unique,
  phone text,
  department text not null default 'Customer Service',
  job_title text not null default 'Insurance Specialist',
  created_at timestamptz not null default now()
);

-- ============================================================
-- 2. Converted Part I Tables
-- ============================================================

create table if not exists public.hwl_customer (
  cust_id integer generated by default as identity primary key,
  user_id uuid unique references public.hwl_app_profile(user_id) on delete set null,
  cust_fname varchar(50) not null,
  cust_lname varchar(50) not null,
  street varchar(150) not null,
  city varchar(50) not null,
  state char(2) not null,
  zip_code varchar(10) not null,
  gender char(1),
  marital_status char(1) not null,
  cust_type char(1) not null,
  email text unique,
  phone text,
  constraint chk_cust_type check (cust_type in ('A', 'H', 'B')),
  constraint chk_gender check (gender in ('M', 'F') or gender is null),
  constraint chk_marital check (marital_status in ('M', 'S', 'W'))
);

comment on table public.hwl_customer is 'Customer master data for NICE insurance services.';
comment on column public.hwl_customer.cust_type is 'Customer type: A=Auto only, H=Home only, B=Both Auto and Home.';

create table if not exists public.hwl_auto_policy (
  policy_id integer generated by default as identity primary key,
  cust_id integer not null references public.hwl_customer(cust_id) on delete restrict,
  start_date date not null,
  end_date date not null,
  premium numeric(10,2) not null,
  policy_status char(1) not null,
  constraint chk_auto_dates check (end_date > start_date),
  constraint chk_auto_policy_status check (policy_status in ('C', 'E')),
  constraint chk_auto_premium check (premium >= 0)
);

comment on table public.hwl_auto_policy is 'Auto insurance policy header; stores current and expired policies.';
comment on column public.hwl_auto_policy.policy_status is 'Policy status: C=Current, E=Expired.';

create table if not exists public.hwl_home_policy (
  policy_id integer generated by default as identity primary key,
  cust_id integer not null references public.hwl_customer(cust_id) on delete restrict,
  start_date date not null,
  end_date date not null,
  premium numeric(10,2) not null,
  policy_status char(1) not null,
  constraint chk_home_dates check (end_date > start_date),
  constraint chk_home_policy_status check (policy_status in ('C', 'E')),
  constraint chk_home_premium check (premium >= 0)
);

comment on table public.hwl_home_policy is 'Home insurance policy header; stores current and expired policies.';

create table if not exists public.hwl_auto_invoice (
  invoice_id integer generated by default as identity primary key,
  policy_id integer not null references public.hwl_auto_policy(policy_id) on delete restrict,
  invoice_date date not null,
  due_date date not null,
  amount numeric(10,2) not null,
  invoice_status text not null default 'unpaid' check (invoice_status in ('unpaid', 'paid', 'overdue')),
  constraint chk_auto_inv_amount check (amount >= 0),
  constraint chk_auto_inv_dates check (due_date >= invoice_date)
);

comment on table public.hwl_auto_invoice is 'Invoices generated for auto insurance policies.';

create table if not exists public.hwl_home_invoice (
  invoice_id integer generated by default as identity primary key,
  policy_id integer not null references public.hwl_home_policy(policy_id) on delete restrict,
  invoice_date date not null,
  due_date date not null,
  amount numeric(10,2) not null,
  invoice_status text not null default 'unpaid' check (invoice_status in ('unpaid', 'paid', 'overdue')),
  constraint chk_home_inv_amount check (amount >= 0),
  constraint chk_home_inv_dates check (due_date >= invoice_date)
);

comment on table public.hwl_home_invoice is 'Invoices generated for home insurance policies.';

create table if not exists public.hwl_auto_payment (
  payment_id integer generated by default as identity primary key,
  invoice_id integer not null references public.hwl_auto_invoice(invoice_id) on delete restrict,
  payment_date date not null,
  pay_method varchar(10) not null,
  constraint chk_auto_pay_method check (pay_method in ('PayPal', 'Credit', 'Debit', 'Check'))
);

comment on table public.hwl_auto_payment is 'Payments applied to auto insurance invoices; installments are allowed.';

create table if not exists public.hwl_home_payment (
  payment_id integer generated by default as identity primary key,
  invoice_id integer not null references public.hwl_home_invoice(invoice_id) on delete restrict,
  payment_date date not null,
  pay_method varchar(10) not null,
  constraint chk_home_pay_method check (pay_method in ('PayPal', 'Credit', 'Debit', 'Check'))
);

comment on table public.hwl_home_payment is 'Payments applied to home insurance invoices; installments are allowed.';

create table if not exists public.hwl_vehicle (
  vin varchar(20) primary key,
  policy_id integer not null references public.hwl_auto_policy(policy_id) on delete restrict,
  make_model_year varchar(100) not null,
  veh_status char(1) not null,
  constraint chk_veh_status check (veh_status in ('L', 'F', 'O'))
);

comment on table public.hwl_vehicle is 'Vehicles insured under an auto policy (1 policy to N vehicles).';

create table if not exists public.hwl_driver (
  license_no varchar(20) primary key,
  vin varchar(20) not null references public.hwl_vehicle(vin) on delete restrict,
  driver_fname varchar(50) not null,
  driver_lname varchar(50) not null,
  age integer not null,
  constraint chk_driver_age check (age >= 16)
);

comment on table public.hwl_driver is 'Drivers associated with an insured vehicle (1 VIN to N drivers).';

create table if not exists public.hwl_home (
  home_id integer generated by default as identity primary key,
  policy_id integer not null references public.hwl_home_policy(policy_id) on delete restrict,
  purchase_date date not null,
  purchase_value numeric(12,2) not null,
  area_sqft integer not null,
  home_type char(1) not null,
  auto_fire_notif integer not null,
  security_system integer not null,
  swimming_pool char(1),
  basement integer not null,
  constraint chk_basement check (basement in (0, 1)),
  constraint chk_fire check (auto_fire_notif in (0, 1)),
  constraint chk_home_area check (area_sqft > 0),
  constraint chk_home_purchase_value check (purchase_value > 0),
  constraint chk_home_type check (home_type in ('S', 'M', 'C', 'T')),
  constraint chk_pool check (swimming_pool in ('U', 'O', 'I', 'M') or swimming_pool is null),
  constraint chk_security check (security_system in (0, 1))
);

comment on table public.hwl_home is 'Homes insured under a home insurance policy (1 policy to N homes).';

-- ============================================================
-- 3. Part II Extension Tables
-- ============================================================

create table if not exists public.hwl_claim (
  claim_id integer generated by default as identity primary key,
  claim_type text not null check (claim_type in ('auto', 'home')),
  auto_policy_id integer references public.hwl_auto_policy(policy_id) on delete restrict,
  home_policy_id integer references public.hwl_home_policy(policy_id) on delete restrict,
  cust_id integer not null references public.hwl_customer(cust_id) on delete restrict,
  assigned_emp_id integer references public.hwl_employee(emp_id) on delete set null,
  claim_amount numeric(10,2) not null check (claim_amount > 0),
  description text not null,
  claim_status text not null default 'submitted' check (claim_status in ('submitted', 'under_review', 'approved', 'rejected', 'paid')),
  submitted_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint chk_claim_one_policy check (
    (claim_type = 'auto' and auto_policy_id is not null and home_policy_id is null)
    or
    (claim_type = 'home' and home_policy_id is not null and auto_policy_id is null)
  )
);

create table if not exists public.hwl_claim_history (
  history_id integer generated by default as identity primary key,
  claim_id integer not null references public.hwl_claim(claim_id) on delete cascade,
  claim_status text not null,
  note text,
  changed_by uuid not null references public.hwl_app_profile(user_id) on delete restrict,
  changed_at timestamptz not null default now()
);

-- ============================================================
-- 4. Indexes
-- ============================================================

create index if not exists idx_hwl_customer_user_id on public.hwl_customer(user_id);
create index if not exists idx_hwl_auto_policy_cust_id on public.hwl_auto_policy(cust_id);
create index if not exists idx_hwl_home_policy_cust_id on public.hwl_home_policy(cust_id);
create index if not exists idx_hwl_auto_invoice_policy_id on public.hwl_auto_invoice(policy_id);
create index if not exists idx_hwl_home_invoice_policy_id on public.hwl_home_invoice(policy_id);
create index if not exists idx_hwl_claim_cust_id on public.hwl_claim(cust_id);
create index if not exists idx_hwl_claim_status on public.hwl_claim(claim_status);

-- ============================================================
-- 5. Helper Functions and Signup Trigger
-- ============================================================

create or replace function public.current_app_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select role from public.hwl_app_profile where user_id = auth.uid()
$$;

create or replace function public.is_employee()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(public.current_app_role() = 'employee', false)
$$;

create or replace function public.current_cust_id()
returns integer
language sql
stable
security definer
set search_path = public
as $$
  select cust_id from public.hwl_customer where user_id = auth.uid()
$$;

create or replace function public.current_emp_id()
returns integer
language sql
stable
security definer
set search_path = public
as $$
  select emp_id from public.hwl_employee where user_id = auth.uid()
$$;

create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_full_name text;
  v_fname text;
  v_lname text;
begin
  v_full_name := coalesce(new.raw_user_meta_data ->> 'full_name', split_part(new.email, '@', 1));
  v_fname := split_part(v_full_name, ' ', 1);
  v_lname := nullif(trim(replace(v_full_name, v_fname, '')), '');
  v_lname := coalesce(v_lname, 'Customer');

  insert into public.hwl_app_profile (user_id, role, email, full_name)
  values (new.id, 'customer', new.email, v_full_name)
  on conflict (user_id) do nothing;

  insert into public.hwl_customer (
    user_id, cust_fname, cust_lname, street, city, state, zip_code,
    gender, marital_status, cust_type, email
  )
  values (
    new.id, v_fname, v_lname, 'Unknown Street', 'New York', 'NY', '10001',
    null, 'S', 'B', new.email
  )
  on conflict (user_id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_auth_user();

create or replace function public.touch_claim_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_touch_claim_updated_at on public.hwl_claim;
create trigger trg_touch_claim_updated_at
before update on public.hwl_claim
for each row execute function public.touch_claim_updated_at();

-- ============================================================
-- 6. Row Level Security
-- ============================================================

alter table public.hwl_app_profile enable row level security;
alter table public.hwl_employee enable row level security;
alter table public.hwl_customer enable row level security;
alter table public.hwl_auto_policy enable row level security;
alter table public.hwl_home_policy enable row level security;
alter table public.hwl_auto_invoice enable row level security;
alter table public.hwl_home_invoice enable row level security;
alter table public.hwl_auto_payment enable row level security;
alter table public.hwl_home_payment enable row level security;
alter table public.hwl_vehicle enable row level security;
alter table public.hwl_driver enable row level security;
alter table public.hwl_home enable row level security;
alter table public.hwl_claim enable row level security;
alter table public.hwl_claim_history enable row level security;

drop policy if exists "profile_select_own_or_employee" on public.hwl_app_profile;
create policy "profile_select_own_or_employee"
on public.hwl_app_profile for select
to authenticated
using (user_id = auth.uid() or public.is_employee());

drop policy if exists "profile_update_own" on public.hwl_app_profile;
create policy "profile_update_own"
on public.hwl_app_profile for update
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists "employee_select_employee" on public.hwl_employee;
create policy "employee_select_employee"
on public.hwl_employee for select
to authenticated
using (user_id = auth.uid() or public.is_employee());

drop policy if exists "customer_select_own_or_employee" on public.hwl_customer;
create policy "customer_select_own_or_employee"
on public.hwl_customer for select
to authenticated
using (user_id = auth.uid() or public.is_employee());

drop policy if exists "customer_update_own_or_employee" on public.hwl_customer;
create policy "customer_update_own_or_employee"
on public.hwl_customer for update
to authenticated
using (user_id = auth.uid() or public.is_employee())
with check (user_id = auth.uid() or public.is_employee());

drop policy if exists "auto_policy_select_own_or_employee" on public.hwl_auto_policy;
create policy "auto_policy_select_own_or_employee"
on public.hwl_auto_policy for select
to authenticated
using (cust_id = public.current_cust_id() or public.is_employee());

drop policy if exists "auto_policy_employee_insert" on public.hwl_auto_policy;
create policy "auto_policy_employee_insert"
on public.hwl_auto_policy for insert
to authenticated
with check (public.is_employee());

drop policy if exists "auto_policy_employee_update" on public.hwl_auto_policy;
create policy "auto_policy_employee_update"
on public.hwl_auto_policy for update
to authenticated
using (public.is_employee())
with check (public.is_employee());

drop policy if exists "home_policy_select_own_or_employee" on public.hwl_home_policy;
create policy "home_policy_select_own_or_employee"
on public.hwl_home_policy for select
to authenticated
using (cust_id = public.current_cust_id() or public.is_employee());

drop policy if exists "home_policy_employee_insert" on public.hwl_home_policy;
create policy "home_policy_employee_insert"
on public.hwl_home_policy for insert
to authenticated
with check (public.is_employee());

drop policy if exists "home_policy_employee_update" on public.hwl_home_policy;
create policy "home_policy_employee_update"
on public.hwl_home_policy for update
to authenticated
using (public.is_employee())
with check (public.is_employee());

drop policy if exists "auto_invoice_select_own_or_employee" on public.hwl_auto_invoice;
create policy "auto_invoice_select_own_or_employee"
on public.hwl_auto_invoice for select
to authenticated
using (
  public.is_employee()
  or exists (
    select 1 from public.hwl_auto_policy p
    where p.policy_id = hwl_auto_invoice.policy_id
      and p.cust_id = public.current_cust_id()
  )
);

drop policy if exists "home_invoice_select_own_or_employee" on public.hwl_home_invoice;
create policy "home_invoice_select_own_or_employee"
on public.hwl_home_invoice for select
to authenticated
using (
  public.is_employee()
  or exists (
    select 1 from public.hwl_home_policy p
    where p.policy_id = hwl_home_invoice.policy_id
      and p.cust_id = public.current_cust_id()
  )
);

drop policy if exists "auto_invoice_employee_write" on public.hwl_auto_invoice;
create policy "auto_invoice_employee_write"
on public.hwl_auto_invoice for all
to authenticated
using (public.is_employee())
with check (public.is_employee());

drop policy if exists "home_invoice_employee_write" on public.hwl_home_invoice;
create policy "home_invoice_employee_write"
on public.hwl_home_invoice for all
to authenticated
using (public.is_employee())
with check (public.is_employee());

drop policy if exists "auto_payment_select_own_or_employee" on public.hwl_auto_payment;
create policy "auto_payment_select_own_or_employee"
on public.hwl_auto_payment for select
to authenticated
using (
  public.is_employee()
  or exists (
    select 1
    from public.hwl_auto_invoice i
    join public.hwl_auto_policy p on p.policy_id = i.policy_id
    where i.invoice_id = hwl_auto_payment.invoice_id
      and p.cust_id = public.current_cust_id()
  )
);

drop policy if exists "home_payment_select_own_or_employee" on public.hwl_home_payment;
create policy "home_payment_select_own_or_employee"
on public.hwl_home_payment for select
to authenticated
using (
  public.is_employee()
  or exists (
    select 1
    from public.hwl_home_invoice i
    join public.hwl_home_policy p on p.policy_id = i.policy_id
    where i.invoice_id = hwl_home_payment.invoice_id
      and p.cust_id = public.current_cust_id()
  )
);

drop policy if exists "vehicle_select_own_or_employee" on public.hwl_vehicle;
create policy "vehicle_select_own_or_employee"
on public.hwl_vehicle for select
to authenticated
using (
  public.is_employee()
  or exists (
    select 1 from public.hwl_auto_policy p
    where p.policy_id = hwl_vehicle.policy_id
      and p.cust_id = public.current_cust_id()
  )
);

drop policy if exists "vehicle_own_or_employee_write" on public.hwl_vehicle;
create policy "vehicle_own_or_employee_write"
on public.hwl_vehicle for all
to authenticated
using (
  public.is_employee()
  or exists (
    select 1 from public.hwl_auto_policy p
    where p.policy_id = hwl_vehicle.policy_id
      and p.cust_id = public.current_cust_id()
  )
)
with check (
  public.is_employee()
  or exists (
    select 1 from public.hwl_auto_policy p
    where p.policy_id = hwl_vehicle.policy_id
      and p.cust_id = public.current_cust_id()
  )
);

drop policy if exists "driver_select_own_or_employee" on public.hwl_driver;
create policy "driver_select_own_or_employee"
on public.hwl_driver for select
to authenticated
using (
  public.is_employee()
  or exists (
    select 1
    from public.hwl_vehicle v
    join public.hwl_auto_policy p on p.policy_id = v.policy_id
    where v.vin = hwl_driver.vin
      and p.cust_id = public.current_cust_id()
  )
);

drop policy if exists "home_select_own_or_employee" on public.hwl_home;
create policy "home_select_own_or_employee"
on public.hwl_home for select
to authenticated
using (
  public.is_employee()
  or exists (
    select 1 from public.hwl_home_policy p
    where p.policy_id = hwl_home.policy_id
      and p.cust_id = public.current_cust_id()
  )
);

drop policy if exists "home_own_or_employee_write" on public.hwl_home;
create policy "home_own_or_employee_write"
on public.hwl_home for all
to authenticated
using (
  public.is_employee()
  or exists (
    select 1 from public.hwl_home_policy p
    where p.policy_id = hwl_home.policy_id
      and p.cust_id = public.current_cust_id()
  )
)
with check (
  public.is_employee()
  or exists (
    select 1 from public.hwl_home_policy p
    where p.policy_id = hwl_home.policy_id
      and p.cust_id = public.current_cust_id()
  )
);

drop policy if exists "claim_select_own_or_employee" on public.hwl_claim;
create policy "claim_select_own_or_employee"
on public.hwl_claim for select
to authenticated
using (cust_id = public.current_cust_id() or public.is_employee());

drop policy if exists "claim_employee_update" on public.hwl_claim;
create policy "claim_employee_update"
on public.hwl_claim for update
to authenticated
using (public.is_employee())
with check (public.is_employee());

drop policy if exists "claim_history_select_own_or_employee" on public.hwl_claim_history;
create policy "claim_history_select_own_or_employee"
on public.hwl_claim_history for select
to authenticated
using (
  public.is_employee()
  or exists (
    select 1 from public.hwl_claim c
    where c.claim_id = hwl_claim_history.claim_id
      and c.cust_id = public.current_cust_id()
  )
);

-- ============================================================
-- 7. RPC Business Functions
-- ============================================================

create or replace function public.submit_auto_claim(
  p_policy_id integer,
  p_claim_amount numeric,
  p_description text
)
returns table (claim_id integer, claim_status text)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_cust_id integer;
  v_policy hwl_auto_policy%rowtype;
  v_claim_id integer;
begin
  v_cust_id := public.current_cust_id();
  if v_cust_id is null then
    raise exception 'Only customers can submit claims';
  end if;

  select * into v_policy
  from public.hwl_auto_policy
  where policy_id = p_policy_id
  for update;

  if not found or v_policy.cust_id <> v_cust_id then
    raise exception 'Auto policy not found or not owned by current customer';
  end if;

  if v_policy.policy_status <> 'C' then
    raise exception 'Only current policies can receive claims';
  end if;

  insert into public.hwl_claim (
    claim_type, auto_policy_id, cust_id, assigned_emp_id,
    claim_amount, description, claim_status
  )
  values (
    'auto',
    p_policy_id,
    v_cust_id,
    (select emp_id from public.hwl_employee order by created_at limit 1),
    p_claim_amount,
    p_description,
    'submitted'
  )
  returning hwl_claim.claim_id into v_claim_id;

  insert into public.hwl_claim_history (claim_id, claim_status, note, changed_by)
  values (v_claim_id, 'submitted', 'Auto claim submitted by customer', auth.uid());

  return query select v_claim_id, 'submitted'::text;
end;
$$;

create or replace function public.submit_home_claim(
  p_policy_id integer,
  p_claim_amount numeric,
  p_description text
)
returns table (claim_id integer, claim_status text)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_cust_id integer;
  v_policy hwl_home_policy%rowtype;
  v_claim_id integer;
begin
  v_cust_id := public.current_cust_id();
  if v_cust_id is null then
    raise exception 'Only customers can submit claims';
  end if;

  select * into v_policy
  from public.hwl_home_policy
  where policy_id = p_policy_id
  for update;

  if not found or v_policy.cust_id <> v_cust_id then
    raise exception 'Home policy not found or not owned by current customer';
  end if;

  if v_policy.policy_status <> 'C' then
    raise exception 'Only current policies can receive claims';
  end if;

  insert into public.hwl_claim (
    claim_type, home_policy_id, cust_id, assigned_emp_id,
    claim_amount, description, claim_status
  )
  values (
    'home',
    p_policy_id,
    v_cust_id,
    (select emp_id from public.hwl_employee order by created_at limit 1),
    p_claim_amount,
    p_description,
    'submitted'
  )
  returning hwl_claim.claim_id into v_claim_id;

  insert into public.hwl_claim_history (claim_id, claim_status, note, changed_by)
  values (v_claim_id, 'submitted', 'Home claim submitted by customer', auth.uid());

  return query select v_claim_id, 'submitted'::text;
end;
$$;

create or replace function public.review_claim(
  p_claim_id integer,
  p_new_status text,
  p_note text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_emp_id integer;
begin
  v_emp_id := public.current_emp_id();
  if v_emp_id is null then
    raise exception 'Only employees can review claims';
  end if;

  if p_new_status not in ('under_review', 'approved', 'rejected', 'paid') then
    raise exception 'Invalid claim review status';
  end if;

  update public.hwl_claim
  set claim_status = p_new_status,
      assigned_emp_id = coalesce(assigned_emp_id, v_emp_id)
  where claim_id = p_claim_id;

  if not found then
    raise exception 'Claim not found';
  end if;

  insert into public.hwl_claim_history (claim_id, claim_status, note, changed_by)
  values (p_claim_id, p_new_status, p_note, auth.uid());
end;
$$;

create or replace function public.pay_auto_invoice(
  p_invoice_id integer,
  p_pay_method varchar
)
returns table (payment_id integer, invoice_status text)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_invoice hwl_auto_invoice%rowtype;
  v_payment_id integer;
begin
  select * into v_invoice
  from public.hwl_auto_invoice
  where invoice_id = p_invoice_id
  for update;

  if not found then
    raise exception 'Auto invoice not found';
  end if;

  if not (
    public.is_employee()
    or exists (
      select 1 from public.hwl_auto_policy p
      where p.policy_id = v_invoice.policy_id
        and p.cust_id = public.current_cust_id()
    )
  ) then
    raise exception 'Not authorized to pay this invoice';
  end if;

  if v_invoice.invoice_status = 'paid' then
    raise exception 'Invoice is already paid';
  end if;

  insert into public.hwl_auto_payment (invoice_id, payment_date, pay_method)
  values (p_invoice_id, current_date, p_pay_method)
  returning hwl_auto_payment.payment_id into v_payment_id;

  update public.hwl_auto_invoice
  set invoice_status = 'paid'
  where invoice_id = p_invoice_id;

  return query select v_payment_id, 'paid'::text;
end;
$$;

create or replace function public.pay_home_invoice(
  p_invoice_id integer,
  p_pay_method varchar
)
returns table (payment_id integer, invoice_status text)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_invoice hwl_home_invoice%rowtype;
  v_payment_id integer;
begin
  select * into v_invoice
  from public.hwl_home_invoice
  where invoice_id = p_invoice_id
  for update;

  if not found then
    raise exception 'Home invoice not found';
  end if;

  if not (
    public.is_employee()
    or exists (
      select 1 from public.hwl_home_policy p
      where p.policy_id = v_invoice.policy_id
        and p.cust_id = public.current_cust_id()
    )
  ) then
    raise exception 'Not authorized to pay this invoice';
  end if;

  if v_invoice.invoice_status = 'paid' then
    raise exception 'Invoice is already paid';
  end if;

  insert into public.hwl_home_payment (invoice_id, payment_date, pay_method)
  values (p_invoice_id, current_date, p_pay_method)
  returning hwl_home_payment.payment_id into v_payment_id;

  update public.hwl_home_invoice
  set invoice_status = 'paid'
  where invoice_id = p_invoice_id;

  return query select v_payment_id, 'paid'::text;
end;
$$;

grant usage on schema public to anon, authenticated;
grant select, insert, update on all tables in schema public to authenticated;
grant execute on all functions in schema public to authenticated;
